# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c5f232ac5ace95bd52fc5addf3205f5590bab822c54fb5ba75e71dadb85b701b3cdb8ff0435fb169a9552cb6d6888804d4e1b1afbc855da002dcb1adaefe733
  twilio_account_sid: AC7335f7568a98f528443b154fb562321c
  twilio_auth_token: 48192852487d55c91319edacc9a3006f
test:
  secret_key_base: 29efebd84caa29dbcd7a9b24421e7b557c6d6ecc5302bca364a601f97e1a5952bac39df83c142e39f12b7a03c0fbf65bb8c556445844d7026fa8f25a4446c60b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

# for use in local environment
# export TWILIO_ACCOUNT_SID=AC7335f7568a98f528443b154fb562321c
# export TWILIO_AUTH_TOKEN=48192852487d55c91319edacc9a3006f
# export SECRET_KEY_BASE=b9677ab4298315aabc4c36b837422aa0220caeb8d9467123f6acd01fe29406397579e94e9dae9d8ea06dcdb39600fec5ad24d379b039e923ef64a7ee0dd0aafe